#!/usr/bin/env python3
"""
sync_gsc_to_sheets.py

Reads the keyword-position scorecard from Google Sheets, queries Google Search
Console for US-only data, finds the best-performing page for each keyword, and
back-fills weekly average positions into the sheet.

Usage:
  python3 sync_gsc_to_sheets.py             # update the sheet
  python3 sync_gsc_to_sheets.py --dry-run   # preview without writing

Authentication (two separate credentials, no shared re-auth needed):
  ┌─ GSC  ─── token.json          generated by:  python3 auth.py
  └─ Sheets ─ service_account.json from Google Cloud Console → IAM → Service Accounts
               Share the spreadsheet with the service account's email address.

Sheet layout (auto-detected):
  Row 1  : "Marketing team | Owner | W14 | W15 | … | W27"   ← week labels
  Row 2  : "Start week | | 2026-04-01 | 2026-04-06 | …"     ← week start dates  ← used
  Row 3  : "End week   | | 2026-04-05 | 2026-04-12 | …"     ← week end dates    ← used
  Row 4+ : keyword rows (col A = keyword; cols C+ = position cells)
           Rows whose col-A starts with "Google position" are formula rows → skipped.

Logic per keyword:
  1. Find the best US page over the full tracked period
     (max clicks; ties broken by impressions).
  2. For each week column, query GSC with that keyword + best page + country=usa
     for the exact [start, end] window and write the aggregate position.
"""

import json
import math
import sys
import time
import warnings
from datetime import date, timedelta, datetime

import gspread
from google.oauth2 import service_account
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import AuthorizedSession

# ── Configuration ──────────────────────────────────────────────────────────────

TOKEN_FILE           = "token.json"           # GSC OAuth token (auth.py)
SERVICE_ACCOUNT_FILE = "service_account.json" # Google service account (Sheets)

SITE          = "sc-domain:openloyalty.io"
GSC_ENDPOINT  = "https://www.googleapis.com/webmasters/v3"

SPREADSHEET_ID = "1-93tOhuhxSqYwl8bLfzXzwj0JgoQuVqbD9VJNvcymbg"

COUNTRY    = "usa"   # GSC ISO 3166-1 alpha-3 (lowercase)
API_SLEEP  = 0.35    # seconds between GSC API calls

# Positions are stored as plain numbers (e.g. 2.7).
# To display them with a comma decimal separator (e.g. 2,7) set the
# spreadsheet locale to Polish / any European locale via:
# Plik → Ustawienia arkusza kalkulacyjnego → Ustawienia regionalne → Polska

# Rows whose column-A value starts with these strings are formula/header rows
# — the script will skip writing positions to them.
SKIP_ROW_PREFIXES = (
    "Google position",
    "Marketing team",
    "Start week",
    "End week",
)

# ── GSC auth ───────────────────────────────────────────────────────────────────


def get_gsc_session() -> AuthorizedSession:
    with open(TOKEN_FILE) as f:
        creds = Credentials.from_authorized_user_info(
            json.load(f),
            scopes=["https://www.googleapis.com/auth/webmasters.readonly"],
        )
    session = AuthorizedSession(creds)
    session.verify = False
    return session


# ── Sheets auth (service account) ─────────────────────────────────────────────


def get_worksheet() -> gspread.Worksheet:
    creds = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE,
        scopes=["https://www.googleapis.com/auth/spreadsheets"],
    )
    gc = gspread.authorize(creds)
    sh = gc.open_by_key(SPREADSHEET_ID)
    return sh.get_worksheet(0)  # first tab


# ── GSC helpers ───────────────────────────────────────────────────────────────


def _gsc_post(session: AuthorizedSession, payload: dict, retries: int = 4) -> list:
    """POST to GSC searchAnalytics with exponential back-off retry."""
    for attempt in range(retries):
        try:
            resp = session.post(
                f"{GSC_ENDPOINT}/sites/{SITE}/searchAnalytics/query",
                json=payload,
            )
            resp.raise_for_status()
            return resp.json().get("rows", [])
        except Exception as exc:
            if attempt == retries - 1:
                raise
            wait = 2 ** (attempt + 1)
            print(f"      ↻ retry {attempt + 1}/{retries - 1} after: {exc}  (wait {wait}s)")
            time.sleep(wait)
    return []


def get_week_position(
    session: AuthorizedSession,
    keyword: str,
    start: str,
    end: str,
) -> tuple[float, str] | tuple[None, None]:
    """
    For the given week, query all US pages that ranked for *keyword*,
    pick the best-performing one (most clicks; ties broken by impressions),
    and return (position, page_url).

    Using a per-week best page avoids stale selection: the page that
    dominated over the full period may not rank in every individual week,
    causing ghost rows (impr=0, pos=0).  Selecting the best page per week
    ensures we always track a page that actually appeared in search results.

    One API call covers both best-page discovery and position retrieval.
    Ghost rows (impressions=0) are filtered out before selection.

    Returns (None, None) when there are no impressions at all that week.
    """
    rows = _gsc_post(session, {
        "startDate":  start,
        "endDate":    end,
        "dimensions": ["page"],
        "dimensionFilterGroups": [{
            "filters": [
                {"dimension": "query",   "operator": "equals", "expression": keyword},
                {"dimension": "country", "operator": "equals", "expression": COUNTRY},
            ]
        }],
        "rowLimit": 25,
    })
    time.sleep(API_SLEEP)

    # Drop ghost rows (impressions=0, position=0) the API occasionally returns
    valid = [r for r in rows if r["impressions"] > 0]
    if not valid:
        return None, None

    best = max(valid, key=lambda r: (r["clicks"], r["impressions"]))
    # Truncate (floor) to 1 decimal — matches how GSC UI displays positions
    pos = math.floor(best["position"] * 10) / 10
    return pos, best["keys"][0]


# ── Date parsing ──────────────────────────────────────────────────────────────

_FMTS = [
    "%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%d.%m.%Y",
    "%Y/%m/%d", "%d-%m-%Y", "%B %d, %Y", "%b %d, %Y",
    "%d %B %Y", "%d %b %Y",
]


def parse_date(s: str) -> date | None:
    s = s.strip()
    for fmt in _FMTS:
        try:
            return datetime.strptime(s, fmt).date()
        except ValueError:
            continue
    return None


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    if dry_run:
        print("🔍  DRY RUN — no changes will be written to the sheet.\n")

    warnings.filterwarnings("ignore", message="Unverified HTTPS request")

    # ── Connect ────────────────────────────────────────────────────────────────
    print("Connecting to Google Search Console…")
    gsc = get_gsc_session()

    print("Connecting to Google Sheets (service account)…")
    ws = get_worksheet()
    print(f"  Opened: '{ws.spreadsheet.title}' → sheet '{ws.title}'")

    # ── Read all values ────────────────────────────────────────────────────────
    all_values = ws.get_all_values()  # list of lists (strings)
    print(f"  Loaded {len(all_values)} rows × {max(len(r) for r in all_values)} cols\n")

    # ── Locate the start-date and end-date rows ────────────────────────────────
    # We look for the rows whose col-A is "Start week" and "End week"
    start_row_idx = end_row_idx = None
    for i, row in enumerate(all_values):
        label = row[0].strip() if row else ""
        if label == "Start week":
            start_row_idx = i
        elif label == "End week":
            end_row_idx = i
        if start_row_idx is not None and end_row_idx is not None:
            break

    if start_row_idx is None or end_row_idx is None:
        print("ERROR: Could not find 'Start week' or 'End week' rows in column A.")
        sys.exit(1)

    start_row = all_values[start_row_idx]
    end_row   = all_values[end_row_idx]

    # ── Build week columns: (col_0idx, start_date, end_date) ─────────────────
    week_cols: list[tuple[int, date, date]] = []
    today = date.today()

    for col_idx in range(2, len(start_row)):  # cols 0=keyword, 1=owner, 2+=weeks
        s_raw = start_row[col_idx] if col_idx < len(start_row) else ""
        e_raw = end_row[col_idx]   if col_idx < len(end_row)   else ""
        s = parse_date(s_raw)
        e = parse_date(e_raw)
        if s and e and s <= today:   # only include weeks that have started
            week_cols.append((col_idx, s, e))

    if not week_cols:
        print("ERROR: No past/current week columns found.")
        sys.exit(1)

    print(f"Week columns to fill ({len(week_cols)} weeks):")
    for col_idx, s, e in week_cols:
        status = "(current)" if s <= today <= e else ""
        print(f"  col {col_idx + 1:2d}  {s}  →  {e}  {status}")

    # ── Collect keyword rows ───────────────────────────────────────────────────
    keyword_rows: list[tuple[int, str]] = []  # (0-indexed row, keyword)
    for row_idx, row in enumerate(all_values):
        kw = row[0].strip() if row else ""
        if not kw:
            continue
        if any(kw.startswith(p) for p in SKIP_ROW_PREFIXES):
            continue
        keyword_rows.append((row_idx, kw))

    print(f"\nKeywords ({len(keyword_rows)}):")
    for _, kw in keyword_rows:
        print(f"  • {kw}")

    # ── Process each keyword ───────────────────────────────────────────────────
    # Collect all updates as {(row_1idx, col_1idx): position_value}
    updates: dict[tuple[int, int], float] = {}

    for row_idx, keyword in keyword_rows:
        print(f"\n{'─' * 64}")
        print(f"Keyword: '{keyword}'")

        found = 0
        for col_idx, week_start, week_end in week_cols:
            pos, page = get_week_position(
                gsc, keyword,
                week_start.isoformat(), week_end.isoformat(),
            )
            if pos is not None:
                found += 1
                print(f"    {week_start}  :  {pos:.1f}  [{page}]")
                updates[(row_idx + 1, col_idx + 1)] = pos   # 1-indexed for gspread
            else:
                print(f"    {week_start}  :  (no data)")

        print(f"  ✓ {found}/{len(week_cols)} weeks have data")

    # ── Write to the sheet ─────────────────────────────────────────────────────
    print(f"\n{'═' * 64}")
    if not updates:
        print("No data to write.")
        return

    if dry_run:
        print(f"Dry run complete. Would write {len(updates)} position values.")
        return

    print(f"Writing {len(updates)} position values to Google Sheets…")

    # Build a batch update list for gspread (Cell objects)
    cell_list = []
    for (sheet_row, sheet_col), pos in updates.items():
        cell = gspread.Cell(sheet_row, sheet_col, pos)
        cell_list.append(cell)

    ws.update_cells(cell_list, value_input_option="RAW")
    print("✅  Sheet updated successfully!")


if __name__ == "__main__":
    main()
